---
regions:
- "global" # This is for all global resource types e.g. IAM
- "eu-west-1"

account-blacklist:
- 1234567890

# optional: restrict nuking to these resources
resource-types:
  targets:
  - IAMUser
  - IAMUserPolicyAttachment
  - IAMUserAccessKey
  - S3Bucket
  - S3Object
  - Route53HostedZone
  - EC2Instance
  - CloudFormationStack
  - MSKCluster

accounts:
  555133742:
    filters:
      IAMUser:
      - "admin"
      IAMUserPolicyAttachment:
      - property: RoleName
        value: "admin"
      IAMUserAccessKey:
      - property: UserName
        value: "admin"
      S3Bucket:
      - "s3://my-bucket"
      S3Object:
      - type: "glob"
        value: "s3://my-bucket/**"
      Route53HostedZone:
      - property: Name
        type: "glob"
        value: "*.zone.loc."
      CloudFormationStack:
      - property: "tag:team"
        value: "myTeam"
      EC2Snapshot:
      - property: "tag:team"
        type: regex
        value: ".+"
      EC2Image:
      - property: "tag:release"
        value: "production"
